# Generated by Django 2.0.2 on 2018-05-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='timestamp',
        ),
    ]
